# Generated by Django 5.2.7 on 2025-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='proof',
            field=models.ImageField(null=True, upload_to='candidate_proofs/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voterid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
