# Generated by Django 5.2.6 on 2026-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0002_remove_candidate_age_remove_voter_age_candidate_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
